lib/top5_web/router.ex
defmodule Top5Web.Router do
  use Top5Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/top5", Top5Web do
    pipe_through :browser

    get     "/",              HomeController,     :index
    post    "/",              HomeController,     :sign_in
    get     "/register",      RegisterController, :index
    post    "/register",      RegisterController, :create
    get     "/tasks",         TaskController,     :index
    get     "/tasks/logout",  TaskController,     :logout
  end

end

lib/top5/tasks/note.ex
defmodule Top5.Tasks.Note do
  use Ecto.Schema
  import Ecto.Changeset


  schema "notes" do
    field :note, :string
    belongs_to :task, Top5.Accounts.Task

    timestamps()
  end

  @doc false
  def changeset(note, attrs) do
    note
    |> cast(attrs, [:note])
    |> validate_required([:note])
  end
end

lib/top5/tasks/task.ex
defmodule Top5.Tasks.Task do
  use Ecto.Schema
  import Ecto.Changeset


  schema "tasks" do
    field :deadline, :naive_datetime
    field :in_backlog, :boolean, default: false
    field :priority, :integer
    field :status, :string
    field :task_description, :string
    field :taskname, :string
    belongs_to :user, Top5.Accounts.User
    has_many :notes, Top5.Tasks.Note

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    task
    |> cast(attrs, [:taskname, :task_description, :status, :in_backlog, :deadline, :priority])
    |> validate_required([:taskname, :task_description, :status, :in_backlog, :deadline, :priority])
  end
end

lib/top5/tasks/tasks.ex
defmodule Top5.Tasks do
  @moduledoc """
  The Tasks context.
  """

  import Ecto.Query, warn: false
  alias Top5.Repo

  alias Top5.Tasks.Task

  @doc """
  Returns the list of tasks.

  ## Examples

      iex> list_tasks()
      [%Task{}, ...]

  """
  def list_tasks do
    Repo.all(Task)
  end

  @doc """
  Gets a single task.

  Raises `Ecto.NoResultsError` if the Task does not exist.

  ## Examples

      iex> get_task!(123)
      %Task{}

      iex> get_task!(456)
      ** (Ecto.NoResultsError)

  """
  def get_task!(id), do: Repo.get!(Task, id)

  @doc """
  Creates a task.

  ## Examples

      iex> create_task(%{field: value})
      {:ok, %Task{}}

      iex> create_task(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_task(attrs \\ %{}) do
    %Task{}
    |> Task.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a task.

  ## Examples

      iex> update_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> update_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_task(%Task{} = task, attrs) do
    task
    |> Task.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Task.

  ## Examples

      iex> delete_task(task)
      {:ok, %Task{}}

      iex> delete_task(task)
      {:error, %Ecto.Changeset{}}

  """
  def delete_task(%Task{} = task) do
    Repo.delete(task)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking task changes.

  ## Examples

      iex> change_task(task)
      %Ecto.Changeset{source: %Task{}}

  """
  def change_task(%Task{} = task) do
    Task.changeset(task, %{})
  end

  alias Top5.Tasks.Note

  @doc """
  Returns the list of notes.

  ## Examples

      iex> list_notes()
      [%Note{}, ...]

  """
  def list_notes do
    Repo.all(Note)
  end

  @doc """
  Gets a single note.

  Raises `Ecto.NoResultsError` if the Note does not exist.

  ## Examples

      iex> get_note!(123)
      %Note{}

      iex> get_note!(456)
      ** (Ecto.NoResultsError)

  """
  def get_note!(id), do: Repo.get!(Note, id)

  @doc """
  Creates a note.

  ## Examples

      iex> create_note(%{task, field: value})
      {:ok, %Note{}}

      iex> create_note(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_note(%Task{} = task, attrs \\ %{}) do
    task
    |> Ecto.build_assoc(:notes)
    |> Note.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a note.

  ## Examples

      iex> update_note(note, %{field: new_value})
      {:ok, %Note{}}

      iex> update_note(note, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_note(%Note{} = note, attrs) do
    note
    |> Note.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Note.

  ## Examples

      iex> delete_note(note)
      {:ok, %Note{}}

      iex> delete_note(note)
      {:error, %Ecto.Changeset{}}

  """
  def delete_note(%Note{} = note) do
    Repo.delete(note)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking note changes.

  ## Examples

      iex> change_note(note)
      %Ecto.Changeset{source: %Note{}}

  """
  def change_note(%Note{} = note) do
    Note.changeset(note, %{})
  end
end

lib/top5_web/controllers/task_controller.ex
defmodule Top5Web.TaskController do
    use Top5Web, :controller

    alias Top5.Accounts
    alias Top5.Tasks
    alias Top5Web.Router.Helpers

    plug :check_auth
  
    def index(conn, _params) do
      tasks = Tasks.list_tasks
      conn
      |> render("index.html", tasks: tasks)
    end

    def logout(conn, _params) do
        conn
        |> delete_session(:current_user_id)
        |> redirect(to: Helpers.home_path(conn, :index))
    end

    defp check_auth(conn, _params) do
        if user_id = get_session(conn, :current_user_id) do
            current_user = Accounts.get_user!(user_id)
            conn
            |> assign(:current_user, current_user)
        else
            conn
            |> clear_flash
            |> put_flash( :error, "Error : You need to login to access the service." )
            |> redirect(to: Helpers.home_path(conn, :index))
        end
    end

  end

lib/top5_web/views/task_view.ex
defmodule Top5Web.TaskView do
    use Top5Web, :view
  end

lib/top5_web/templates/task/index.html.eex
<style>
#add-task-modal-close {
    text-decoration:none;
    cursor:pointer;
    padding:15px;
    color: #ef9a9a;
}
#add-task-modal-close:hover {
    color: red;
}
</style>

<div class="row">
    <div class="col s8 offset-s2">
        <div>
            <h3><span style="border-bottom: 4px solid lightblue;">Task List</span></h3>
        </div>
        <div>
            <%= if Enum.count(@tasks) > 0 do %>
                <%= for task <- @tasks do %>
                    <p><%= task.task_description %></p>
                    <!--<p style="font-size:22px;">No active tasks have been defined.</p>-->
                <% end %>
            <% else %>
                <p style="font-size:22px;">No active tasks have been defined.</p>
            <% end %>
        </div>
    </div>
</div>

<div id="add-task-modal" class="modal bottom-sheet" style='z-index:1003;display:none;opacity:0;bottom:-100%;min-height:80%;max-height:90%;border-top:8px solid #000;opacity:0.7;'>
    <div class="modal-content">
        <div style="position:absolute; top:15px;right:60px;">
            <a id="add-task-modal-close" href="#">
                <i class="material-icons" style="font-size:5rem;">close</i>
            </a>
        </div>
        <div style="border-bottom:2px solid lightblue;">
            <h2 style="margin-left:40px;">Add Task</h2>
        </div>
        <form>
        </form>
    </div>
</div>

<div class="sidebar">
    <div style="margin:90px 0 10px 0;">
        <h2 class="menu-title"><span style="border-bottom: 1px solid #3bc492;">Menu</span></h2>
        <%= link to: Routes.task_path(@conn, :logout) do %>
            <i class="material-icons" style="font-size:4rem;margin-top:30px;margin-left:20px;color:#000;">power_settings_new</i>
        <% end %>
        <a href="#add-task-modal" class="modal-trigger"><i class="material-icons" style="font-size:4rem;margin-top:10px;margin-left:20px;color:#000;">comment</i></a>
        <a href="#"><i class="material-icons" style="font-size:4rem;margin-top:10px;margin-left:20px;color:#000;">storage</i></a>
        <a href="#"><i class="material-icons" style="font-size:4rem;margin-top:10px;margin-left:20px;color:#000;">done</i></a>
    </div>
</div>

<script>
    $( document ).ready(function() {
        $('.modal').modal({outDuration:300,opacity:.4})
    });

    $('#add-task-modal-close').on('click', function(e) {
        e.preventDefault();
        $('#add-task-modal').modal('close');
    });
</script>