lib/top5_web/router.ex
defmodule Top5Web.Router do
  use Top5Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/top5", Top5Web do
    pipe_through :browser

    get     "/",              HomeController,     :index
    post    "/",              HomeController,     :sign_in
    get     "/register",      RegisterController, :index
    post    "/register",      RegisterController, :create
    get     "/tasks",         TaskController,     :index
    get     "/tasks/logout",  TaskController,     :logout
  end

end

lib/top5_web/controllers/register_controller.ex
defmodule Top5Web.RegisterController do
  use Top5Web, :controller

  alias Top5.Accounts
  alias Top5.Accounts.User
  alias Top5Web.Router.Helpers

  def index(conn, params) do
    changeset = User.changeset(%User{}, params);
    conn
    |> put_flash( :info, "Enter all details to sign-up for this service.")
    |> render("index.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> clear_flash
        |> put_session(:current_user_id, user.id)
        |> put_flash( :info, "User created successfully" )
        |> redirect(to: Helpers.task_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        { fld, {msg, _} } = List.first(changeset.errors)
        conn
        |> clear_flash
        |> put_flash( :error, "Error : #{String.capitalize(Atom.to_string(fld))} - #{msg}" )
        |> render("index.html", changeset: changeset)
    end
  end

end

lib/top5_web/views/register_view.ex
defmodule Top5Web.RegisterView do
  use Top5Web, :view
end

lib/top5_web/templates/register/index.html.eex

<div class="row">
    <div class="col s8 offset-s3">
        <div class="login-form">
            <div class="col s10">
                <%= if get_flash(@conn, :info) do %>
                    <p class="info_message"><%= get_flash(@conn, :info) %></p>
                <% end %>  
                <%= if get_flash(@conn, :error) do %>
                    <p class="error_message"><%= get_flash(@conn, :error) %></p>
                <% end %>    
            </div>
            <div class="col s12" style="padding-top:25px;">
                <%= form_for @changeset, Routes.register_path(@conn, :create), fn f -> %>
                    <div class="row">
                        <div class="input-field col s8">
                            <i class="material-icons prefix">account_circle</i>
                            <%= text_input f, :username, autofocus: true %>
                            <%= label f, :username, "Username", class: "active" %>
                        </div>
                    </div>
                     <div class="row">
                        <div class="input-field col s8">
                            <i class="material-icons prefix">account_circle</i>
                            <%= text_input f, :email %>
                            <%= label f, :email, "Email", class: "active" %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s8">
                            <i class="material-icons prefix">vpn_key</i>
                            <%= password_input f, :password %>
                            <%= label f, :password, "Password", class: "active" %>
                        </div>
                    </div>
                     
                    <div class="row">
                        <div class="col s6">
                            <%= submit "Register", class: "btn-large waves-effect waves-light login-button" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>