lib/top5_web/router.ex
defmodule Top5Web.Router do
  use Top5Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/top5", Top5Web do
    pipe_through :browser

    get     "/",              HomeController,     :index
    post    "/",              HomeController,     :sign_in
    get     "/register",      RegisterController, :index
    post    "/register",      RegisterController, :create
    get     "/tasks",         TaskController,     :index
    get     "/tasks/logout",  TaskController,     :logout
  end

end

lib/top5_web/controllers/home_controller.ex
defmodule Top5Web.HomeController do
  use Top5Web, :controller

  alias Top5.Accounts
  alias Top5Web.Router.Helpers

  def index(conn, _params) do
    conn
    |> put_flash( :info, "Login using your Username / Password")
    |> render("index.html")
  end

  def sign_in(conn, %{"session" => auth_params}) do
    username = auth_params["username"]
    password = auth_params["password"]

    with {:ok, _ } <- validate_signin(auth_params),    
         {:ok, user} <- authenticate_user(username, password)
    do
      conn
        |> clear_flash
        |> put_session(:current_user_id, user.id)
        |> put_flash( :info, "Signedin successfully" )
        |> redirect(to: Helpers.task_path(conn, :index))
    else
      _ -> conn
        |> clear_flash
        |> put_flash( :error, "Error - Username or Password is missing / incorrect" )
        |> render("index.html")
    end
  end

  defp authenticate_user(username, password) do
    case user = Accounts.get_user_by_username(username) do
      nil ->
        {:error, :invalid_data}
      user ->
        if Pbkdf2.verify_pass(password, user.password) do
          IO.puts "auth - success"
          {:ok, user}
        else
          IO.puts "auth - failed"
          {:error, :invalid_data}
        end
    end
  end

  defp validate_signin(params) do
    case ( Map.values(params) == ["",""] ) do 
      true ->
        {:error, 'error'}
      false ->
        {:ok, 'success'}
    end
  end

end

lib/top5_web/views/home_view.ex
defmodule Top5Web.HomeView do
  use Top5Web, :view
end

lib/top5_web/templates/home/index.html.eex

<div class="row">
    <div class="col s8 offset-s3">
        <div class="login-form">
            <div class="col s10 message">
                <%= if get_flash(@conn, :error) do %>
                    <p class="error_message"><%= get_flash(@conn, :error) %></p>
                <% else %>
                    <%= if get_flash(@conn, :info) do %>
                            <p class="info_message"><%= get_flash(@conn, :info) %></p>
                    <% end %>
                <% end %>  
            </div>
            <div class="col s12"style="margin-top:20px;">
                <%= form_for @conn, Routes.home_path(@conn, :sign_in), [as: :session], fn f -> %>
                    <div class="row">
                        <div class="input-field col s8">
                            <i class="material-icons prefix">account_circle</i>
                            <%= text_input f, :username, autofocus: true %>
                            <%= label f, :username, "Username", class: "active" %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s8">
                            <i class="material-icons prefix">vpn_key</i>
                            <%= password_input f, :password %>
                            <%= label f, :password, "Password", class: "active" %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s6">
                            <%= submit "Login", class: "btn-large waves-effect waves-light login-button" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col s8 offset-s3">
        <h5>To register for this service - click <a href="/top5/register" ><span style="border-bottom: 2px solid lightblue;">here</span></h5>
    </div>
</div>